version: '3'
services:
  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
  postgres:
    image: postgres:9.5
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - /Users/anton/pg_data:/Users/anton/pg_data
    environment:
      - POSTGRES_PASSWORD=12345
      - PGDATA=/Users/anton/pg_data
      - POSTGRES_USER=postgres
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq-container
    image: rabbitmq:3.6.2-management
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
  migrations:
    image: anton1987/migrations_demo
    depends_on:
      - postgres
    command: ["wait-for-it.sh", "db:5432"]
  patient:
    image: anton1987/patients_demo
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - postgres
      - redis
      - rabbitmq
    command: ["wait-for-it.sh", "db:5432"]
